version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: python_app_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: crypto_data
    volumes:
      - mysql_data:/var/lib/mysql
    networks: -backend

  web:
    build: .
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
