version: "3.8"

services:
  db:
    image: mysql:8.0

    container_name: mysql_container

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}

      # Remove MYSQL_USER and MYSQL_PASSWORD if only using root

      # Uncomment and set these if you need a non-root user

      # MYSQL_USER: ${MYSQL_NON_ROOT_USERNAME}

      # MYSQL_PASSWORD: ${MYSQL_NON_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - backend

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

      interval: 10s

      timeout: 5s

      retries: 5

      start_period: 30s

  web:
    build: .

    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}

      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}

      - MYSQL_USERNAME=${MYSQL_USERNAME} # Use the non-root username or root if intended

      - MYSQL_PASSWORD=${MYSQL_PASSWORD} # Use the corresponding password

      - MYSQL_DATABASE=${MYSQL_DATABASE}

    volumes:
      - .:/app

    ports:
      - "5001:5001"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
